---
ci:
  # format compatible with commitlint
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
  autoupdate_schedule: monthly
  autofix_commit_msg: "chore: auto fixes from pre-commit.com hooks"
  skip:
    # https://github.com/pre-commit-ci/issues/issues/55
    - pip-compile
  submodules: true
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort-fix

  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: 1.5.0
    hooks:
      - id: tox-ini-fmt

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.7"
    hooks:
      - id: ruff
        entry: sh -c 'ruff check --fix --force-exclude && ruff format --force-exclude'
        types_or: [python, pyi]
  - repo: https://github.com/asottile/pyupgrade
    # keep it after flake8
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: ["--py310-plus"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^src/tendo/tests/.*\.txt$
      - id: end-of-file-fixer
        exclude: ^src/tendo/tests/.*\.txt$
      - id: mixed-line-ending
        exclude: ^src/tendo/tests/.*\.txt$
      - id: check-byte-order-marker
        exclude: ^src/tendo/tests/.*\.txt$
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-yaml
        files: .*\.(yaml|yml)$
        exclude: >
          (?x)^(
            mkdocs.yml
          )$
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$

  - # keep at bottom as these are slower
    repo: local
    hooks:
      - id: deps
        name: Upgrade constraints files and requirements
        files: ^(pyproject\.toml|.config/.*)$
        always_run: true
        language: python
        entry: python3 -m uv pip compile -q --all-extras --python-version=3.10 --output-file=.config/constraints.txt pyproject.toml --upgrade
        pass_filenames: false
        stages:
          - manual
        additional_dependencies:
          - uv>=0.6.6
      - id: pip-compile
        name: Check constraints files and requirements
        files: ^(pyproject\.toml|\.config/.*)$
        language: python
        entry: uv pip compile -q --all-extras --python-version=3.10 --output-file=.config/constraints.txt pyproject.toml
        pass_filenames: false
        additional_dependencies:
          - uv>=0.6.6
