---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: ^src/tendo/tests/.*\.txt$
      - id: end-of-file-fixer
        exclude: ^src/tendo/tests/.*\.txt$
      - id: mixed-line-ending
        exclude: ^src/tendo/tests/.*\.txt$
      - id: check-byte-order-marker
        exclude: ^src/tendo/tests/.*\.txt$
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-yaml
        files: .*\.(yaml|yml)$
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
