#!/bin/bash
#set -e

echo === unittests ===
#python setup.py test

tox --version >/dev/null 2>&1 || {
    sudo easy_install tox || echo >&2 "I require tox but it's not installed and I wasn't able to install it.  Aborting."; exit 1;
    }


# autopep8
echo === autopep8  ===
autopep8 --version >/dev/null 2>&1 || {
    sudo easy_install autopep8 || echo >&2 "I require pep8 but it's not installed and I wasn't able to install it.  Aborting."; exit 1;
    }

# pep8
echo === pep8  ===
pep8 --version >/dev/null 2>&1 || {
    sudo easy_install pep8 || echo >&2 "I require pep8 but it's not installed and I wasn't able to install it.  Aborting."; exit 1;
    }

echo === py.test  ===
py.test -d >/dev/null 2>&1
if [[ $? -eq 127 ]]; then
    sudo easy_install pytest pytest-xdist
else
  if [[ $? -eq 2 ]]; then
    sudo easy_install pytest-xdist
  fi
fi


#2>&1 || {
#    sudo easy_install pytest pytest-xdist
#}