[tool.coverage.run]
source_pkgs = ["tendo"]
branch = true
parallel = true
concurrency = ["multiprocessing", "thread"]

[tool.coverage.paths]
source = ["src", ".tox/*/site-packages"]

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "if TYPE_CHECKING:"]
