#!/bin/bash
source prepare
set -e

echo === running unittests ===
#python setup.py test
tox

echo === autopep8 ===
autopep8 --ignore=E501 -i *.py scripts/*.py scripts/*/*.py scripts/lib/*/*.py   

echo === running pep8  ===
pep8

# TODO: run autopep8 ?!

