---
name: tox

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: # needed for tox.yml workflow
  checks: read
  contents: read
  id-token: write
  packages: write
  pull-requests: write
jobs:
  tox:
    uses: ansible/team-devtools/.github/workflows/tox.yml@main
    with:
      other_names: |
        docs
        lint
        pkg
